<!--


    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<!DOCTYPE assembly [
        <!ELEMENT assembly (id|includeBaseDirectory|baseDirectory|formats|fileSets|dependencySets)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT includeBaseDirectory (#PCDATA)>
        <!ELEMENT baseDirectory (#PCDATA)>
        <!ELEMENT formats (format)*>
        <!ELEMENT format (#PCDATA)>
        <!ELEMENT fileSets (fileSet)*>
        <!ELEMENT fileSet (directory|outputDirectory|fileMode|includes)*>
        <!ELEMENT directory (#PCDATA)>
        <!ELEMENT outputDirectory (#PCDATA)>
        <!ELEMENT includes (include)*>
        <!ELEMENT include (#PCDATA)>
        <!ELEMENT dependencySets (dependencySet)*>
        <!ELEMENT dependencySet (outputDirectory|outputFileNameMapping|includes)*>
        ]>
<assembly>
    <id>bin</id>
    <includeBaseDirectory>true</includeBaseDirectory>
    <baseDirectory>${api.server.dist.name}</baseDirectory>
    <formats>
        <format>tar.gz</format>
        <format>zip</format>
    </formats>

    <fileSets>

        <!-- ********************** copy release notes files ********************** -->
        <fileSet>
            <directory>../../../</directory>
            <outputDirectory>.</outputDirectory>
            <includes>
                <include>RELEASE_NOTES</include>
            </includes>
        </fileSet>
        <!-- ********************** copy licenses, readme etc. ********************** -->
        <fileSet>
            <directory>src/main/resources/api-server</directory>
            <outputDirectory>.</outputDirectory>
            <includes>
                <include>LICENSE</include>
                <include>NOTICE</include>
                <include>README</include>
                <include>INSTALL</include>
            </includes>
        </fileSet>

        <!-- ********************** copy database scripts ********************** -->
        <fileSet>
            <directory>../registry/registry-core/src/main/resources/
            </directory>
            <outputDirectory>bin/database_scripts
            </outputDirectory>
            <includes>
                <include>*sql*</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>../credential-store/credential-store-service/src/main/resources/
            </directory>
            <outputDirectory>bin/database_scripts
            </outputDirectory>
            <includes>
                <include>*sql*</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>../sharing-registry/sharing-registry-server/src/main/resources/
            </directory>
            <outputDirectory>bin/database_scripts
            </outputDirectory>
            <includes>
                <include>*sql*</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>../../airavata-services/profile-service/profile-user-core/src/main/resources/
            </directory>
            <outputDirectory>bin/database_scripts
            </outputDirectory>
            <includes>
                <include>*sql*</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>src/main/resources/api-server/bin</directory>
            <outputDirectory>bin</outputDirectory>
            <fileMode>777</fileMode>
            <includes>
                <include>*.sh</include>
                <include>*.bat</include>
                <include>logo.txt</include>
                <include>startNetworkServer</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>${project.build.directory}/conf</directory>
            <outputDirectory>bin</outputDirectory>
            <includes>
                <include>airavata-server.properties</include>
                <include>zoo.cfg</include>
                <include>registry.properties</include>
                <include>logback.xml</include>
                <include>host.xml</include>
                <include>persistence.xml</include>
                <include>provenance.sql</include>
                <include>gfac-config.yaml</include>
                <include>PBS_Groovy.template</include>
                <include>SLURM_Groovy.template</include>
                <include>LSF_Groovy.template</include>
                <include>UGE_Groovy.template</include>
                <include>FORK_Groovy.template</include>
                <include>gsissh.properties</include>
                <include>airavata.jks</include>
                <include>client_truststore.jks</include>
                <include>airavata-default-xacml-policy.xml</include>
            </includes>
        </fileSet>

        <!-- Create logs directory -->
        <fileSet>
            <directory>./</directory>
            <outputDirectory>logs</outputDirectory>
            <excludes>
                <exclude>*/**</exclude>
            </excludes>
        </fileSet>
    </fileSets>

    <dependencySets>
        <dependencySet>
            <useProjectArtifact>false</useProjectArtifact>
            <outputDirectory>lib</outputDirectory>
            <outputFileNameMapping>${artifact.artifactId}.${artifact.extension}</outputFileNameMapping>
            <includes>
                <include>org.apache.derby:derby:jar</include>
                <include>org.apache.derby:derbytools:jar</include>
                <include>org.apache.derby:derbynet:jar</include>
                <include>org.apache.derby:derbyclient:jar</include>
            </includes>
        </dependencySet>
        <dependencySet>
            <useProjectArtifact>false</useProjectArtifact>
            <outputDirectory>lib</outputDirectory>
            <includes>
<!--                <include>*:*:jar</include>-->
                <include>org.apache.httpcomponents:httpcore</include>
                <include>io.grpc:grpc-context</include>
                <include>org.apache.openjpa:openjpa</include>
                <include>xml-apis:xml-apis</include>
                <include>com.beust:jcommander</include>
                <include>javax.servlet:servlet-api</include>
                <include>org.apache.airavata:profile-user-core</include>
                <include>jakarta.validation:jakarta.validation-api</include>
                <include>org.springframework.boot:spring-boot-starter-aop</include>
                <include>log4j:log4j</include>
                <include>org.apache.airavata:registry-api-service</include>
                <include>org.springframework.boot:spring-boot-starter-tomcat</include>
                <include>org.apache.airavata:airavata-data-models</include>
                <include>junit:junit</include>
                <include>io.kubernetes:client-java-proto</include>
                <include>org.jboss.logging:jboss-logging</include>
                <include>io.zipkin.brave:brave</include>
                <include>org.keycloak:keycloak-core</include>
                <include>org.apache.custos:resource-secret-management-client</include>
                <include>io.netty:netty-codec-http2</include>
                <include>org.apache.airavata:iam-admin-services-core</include>
                <include>com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider</include>
                <include>io.zipkin.reporter2:zipkin-sender-kafka</include>
                <include>org.bouncycastle:bcprov-ext-jdk15on</include>
                <include>org.apache.tomcat.embed:tomcat-embed-websocket</include>
                <include>io.zipkin.brave:brave-instrumentation-http</include>
                <include>org.apache.custos:sharing-core-service-client-stub</include>
                <include>org.apache.airavata:airavata-credential-store-stubs</include>
                <include>com.google.api.grpc:proto-google-common-protos</include>
                <include>commons-io:commons-io</include>
                <include>org.apache.custos:custos-logging-client-stub</include>
                <include>org.apache.logging.log4j:log4j-to-slf4j</include>
                <include>org.apache.airavata:airavata-orchestrator-client</include>
                <include>io.kubernetes:client-java-api</include>
                <include>org.apache.custos:group-management-client</include>
                <include>org.apache.derby:derbyclient</include>
                <include>org.apache.custos:resource-secret-core-service-client-stub</include>
                <include>org.springframework.boot:spring-boot-actuator</include>
                <include>com.google.code.gson:gson</include>
                <include>org.apache.airavata:platform-monitoring</include>
                <include>com.google.inject:guice</include>
                <include>com.rabbitmq:amqp-client</include>
                <include>org.apache.airavata:compute-account-provisioning</include>
                <include>io.zipkin.brave:brave-instrumentation-kafka-clients</include>
                <include>org.apache.custos:custos-integration-services-commons</include>
                <include>org.apache.shiro:shiro-core</include>
                <include>org.bouncycastle:bcprov-jdk15on</include>
                <include>org.apache.custos:iam-admin-core-service-client-stub</include>
                <include>org.aspectj:aspectjweaver</include>
                <include>javax.ws.rs:javax.ws.rs-api</include>
                <include>org.apache.airavata:airavata-registry-core</include>
                <include>org.apache.geronimo.specs:geronimo-jta_1.1_spec</include>
                <include>org.apache.custos:tenant-management-client</include>
                <include>edu.uiuc.ncsa.myproxy:oa4mp-client-loader-oauth1</include>
                <include>io.perfmark:perfmark-api</include>
                <include>javax.inject:javax.inject</include>
                <include>org.slf4j:slf4j-api</include>
                <include>org.jboss.resteasy:resteasy-client</include>
                <include>commons-logging:commons-logging</include>
                <include>org.springframework.cloud:spring-cloud-config-client</include>
                <include>org.apache.kafka:kafka-clients</include>
                <include>com.jcraft:jsch</include>
                <include>org.apache.custos:credential-store-core-service-client-stubs</include>
                <include>org.ogce:xpp3</include>
                <include>org.apache.curator:curator-client</include>
                <include>commons-pool:commons-pool</include>
                <include>com.fasterxml.jackson.datatype:jackson-datatype-jdk8</include>
                <include>org.apache.oltu.oauth2:org.apache.oltu.oauth2.client</include>
                <include>org.apache.airavata:profile-service-commons</include>
                <include>org.jboss.resteasy:resteasy-jackson2-provider</include>
                <include>org.apache.airavata:airavata-registry-cpi</include>
                <include>io.zipkin.brave:brave-instrumentation-spring-web</include>
                <include>org.springframework.security:spring-security-rsa</include>
                <include>io.prometheus:simpleclient_httpserver</include>
                <include>org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.0_spec</include>
                <include>io.netty:netty-transport</include>
                <include>edu.uiuc.ncsa.security:ncsa-security-storage</include>
                <include>org.apache.custos:tenant-profile-core-service-client-stub</include>
                <include>com.fasterxml.jackson.jaxrs:jackson-jaxrs-base</include>
                <include>commons-beanutils:commons-beanutils</include>
                <include>org.apache.airavata:airavata-server-configuration</include>
                <include>org.apache.commons:commons-email</include>
                <include>io.grpc:grpc-protobuf</include>
                <include>org.springframework.cloud:spring-cloud-starter-config</include>
                <include>org.apache.airavata:airavata-sharing-registry-stubs</include>
                <include>org.keycloak:keycloak-admin-client</include>
                <include>edu.uiuc.ncsa.security:ncsa-security-util</include>
                <include>org.springframework:spring-beans</include>
                <include>io.micrometer:micrometer-core</include>
                <include>org.joda:joda-convert</include>
                <include>org.apache.custos:sharing-management-client</include>
                <include>org.slf4j:jcl-over-slf4j</include>
                <include>org.apache.geronimo.specs:geronimo-jpa_2.2_spec</include>
                <include>com.fasterxml.jackson.core:jackson-annotations</include>
                <include>io.grpc:grpc-services</include>
                <include>com.google.re2j:re2j</include>
                <include>org.apache.custos:resource-secret-management-service</include>
                <include>javax.mail:mail</include>
                <include>org.apache.custos:custos-integration-core</include>
                <include>org.springframework.cloud:spring-cloud-starter-sleuth</include>
                <include>io.zipkin.brave:brave-instrumentation-httpasyncclient</include>
                <include>io.prometheus:simpleclient_pushgateway</include>
                <include>org.apache.custos:agent-management-service</include>
                <include>io.netty:netty-handler-proxy</include>
                <include>com.squareup.okio:okio</include>
                <include>org.slf4j:log4j-over-slf4j</include>
                <include>org.apache.zookeeper:zookeeper</include>
                <include>org.apache.airavata:profile-service-server</include>
                <include>org.json:json</include>
                <include>io.zipkin.brave:brave-instrumentation-spring-rabbit</include>
                <include>com.google.errorprone:error_prone_annotations</include>
                <include>io.opencensus:opencensus-contrib-grpc-metrics</include>
                <include>io.swagger:swagger-annotations</include>
                <include>com.google.protobuf:protobuf-java</include>
                <include>io.zipkin.zipkin2:zipkin</include>
                <include>io.zipkin.brave:brave-instrumentation-jms</include>
                <include>org.apache.airavata:airavata-api-stubs</include>
                <include>org.apache.geronimo.specs:geronimo-jms_1.1_spec</include>
                <include>edu.uiuc.ncsa.security.delegation:ncsa-security-delegation-common</include>
                <include>org.jboss.resteasy:resteasy-jaxrs</include>
                <include>org.apache.airavata:airavata-client-configuration</include>
                <include>org.springframework.boot:spring-boot-starter-validation</include>
                <include>org.springframework:spring-context</include>
                <include>com.google.guava:guava</include>
                <include>jline:jline</include>
                <include>org.apache.airavata:cluster-monitoring</include>
                <include>edu.uiuc.ncsa.security:ncsa-security-servlet</include>
                <include>edu.uiuc.ncsa.security:ncsa-security-core</include>
                <include>org.apache.oltu.oauth2:org.apache.oltu.oauth2.common</include>
                <include>org.springframework:spring-web</include>
                <include>org.apache.custos:identity-management-service</include>
                <include>org.apache.custos:custos-clients-core</include>
                <include>org.apache.custos:cluster-management-core-service-client-stub</include>
                <include>io.netty:netty-codec-socks</include>
                <include>org.apache.custos:identity-core-service-client-stub</include>
                <include>org.apache.custos:custos-java-sdk</include>
                <include>org.apache.custos:tenant-management-service</include>
                <include>commons-digester:commons-digester</include>
                <include>io.grpc:grpc-netty</include>
                <include>org.slf4j:jul-to-slf4j</include>
                <include>org.yaml:snakeyaml</include>
                <include>org.apache.commons:commons-pool2</include>
                <include>commons-dbcp:commons-dbcp</include>
                <include>org.apache.derby:derbynet</include>
                <include>io.sundr:builder-annotations</include>
                <include>edu.uiuc.ncsa.myproxy:oa4mp-client-api</include>
                <include>org.apache.airavata:airavata-orchestrator-service</include>
                <include>org.apache.commons:commons-lang3</include>
                <include>org.keycloak:keycloak-common</include>
                <include>io.zipkin.brave:brave-instrumentation-httpclient</include>
                <include>org.apache.airavata:registry-api-stubs</include>
                <include>org.codehaus.mojo:animal-sniffer-annotations</include>
                <include>org.springframework.boot:spring-boot-starter-web</include>
                <include>org.springframework.boot:spring-boot-autoconfigure</include>
                <include>org.apache.airavata:profile-tenant-core</include>
                <include>net.oauth.core:oauth-provider</include>
                <include>jakarta-regexp:jakarta-regexp</include>
                <include>edu.uiuc.ncsa.myproxy:myproxy-logon</include>
                <include>ch.qos.logback:logback-core</include>
                <include>com.codahale:shamir</include>
                <include>org.apache.airavata:airavata-orchestrator-core</include>
                <include>org.apache.custos:user-management-service</include>
                <include>org.springframework.boot:spring-boot</include>
                <include>org.apache.tomcat.embed:tomcat-embed-el</include>
                <include>org.springframework.cloud:spring-cloud-starter</include>
                <include>org.apache.thrift:libthrift</include>
                <include>org.springframework:spring-aop</include>
                <include>commons-codec:commons-codec</include>
                <include>org.bouncycastle:bcpkix-jdk15on</include>
                <include>io.grpc:grpc-stub</include>
                <include>io.zipkin.brave:brave-context-log4j2</include>
                <include>io.grpc:grpc-protobuf-lite</include>
                <include>org.databene:contiperf</include>
                <include>org.apache.airavata:airavata-model-utils</include>
                <include>com.squareup.okhttp:okhttp-ws</include>
                <include>com.fasterxml.jackson.datatype:jackson-datatype-jsr310</include>
                <include>io.micrometer:micrometer-registry-prometheus</include>
                <include>org.apache.custos:user-profile-core-service-client-stub</include>
                <include>joda-time:joda-time</include>
                <include>org.springframework.boot:spring-boot-starter-json</include>
                <include>org.apache.mina:mina-core</include>
                <include>com.fasterxml.jackson.core:jackson-core</include>
                <include>com.google.protobuf:protobuf-java-util</include>
                <include>org.apache.airavata:airavata-credential-store</include>
                <include>commons-httpclient:commons-httpclient</include>
                <include>org.apache.airavata:airavata-commons</include>
                <include>javax.activation:activation</include>
                <include>org.springframework.boot:spring-boot-starter</include>
                <include>org.latencyutils:LatencyUtils</include>
                <include>org.springframework.boot:spring-boot-starter-actuator</include>
                <include>io.prometheus:simpleclient</include>
                <include>io.netty:netty-codec</include>
                <include>io.netty:netty-resolver</include>
                <include>org.testng:testng</include>
                <include>edu.uiuc.ncsa.security.delegation:ncsa-security-oauth-1.0a</include>
                <include>org.xerial.snappy:snappy-java</include>
                <include>io.zipkin.brave:brave-instrumentation-servlet</include>
                <include>org.apache.airavata:profile-service-stubs</include>
                <include>org.apache.custos:identity-management-client</include>
                <include>org.apache.airavata:airavata-api-server</include>
                <include>commons-cli:commons-cli</include>
                <include>org.codehaus.jackson:jackson-core-asl</include>
                <include>org.apache.ibatis:ibatis-sqlmap</include>
                <include>javax.annotation:javax.annotation-api</include>
                <include>io.opencensus:opencensus-api</include>
                <include>io.github.lognet:grpc-spring-boot-starter</include>
                <include>io.sundr:resourcecify-annotations</include>
                <include>org.apache.curator:curator-framework</include>
                <include>org.apache.airavata:airavata-standalone-server</include>
                <include>io.grpc:grpc-api</include>
                <include>org.apache.commons:commons-compress</include>
                <include>net.sourceforge.serp:serp</include>
                <include>org.apache.custos:sharing-management-service</include>
                <include>com.fasterxml:classmate</include>
                <include>org.springframework.boot:spring-boot-starter-logging</include>
                <include>org.springframework.cloud:spring-cloud-commons</include>
                <include>org.quartz-scheduler:quartz</include>
                <include>io.zipkin.brave:brave-instrumentation-grpc</include>
                <include>org.hamcrest:hamcrest-core</include>
                <include>org.apache.logging.log4j:log4j-api</include>
                <include>com.squareup.okhttp:okhttp</include>
                <include>org.apache.airavata:airavata-security</include>
                <include>org.apache.derby:derbytools</include>
                <include>org.apache.custos:agent-profile-core-service-client-stub</include>
                <include>io.zipkin.reporter2:zipkin-reporter</include>
                <include>commons-collections:commons-collections</include>
                <include>org.apache.custos:agent-management-client</include>
                <include>org.springframework:spring-jcl</include>
                <include>edu.uiuc.ncsa.security.delegation:ncsa-security-delegation-client</include>
                <include>org.apache.servicemix.bundles:org.apache.servicemix.bundles.dom4j</include>
                <include>io.prometheus:simpleclient_common</include>
                <include>com.squareup.okhttp:logging-interceptor</include>
                <include>org.apache.tomcat.embed:tomcat-embed-core</include>
                <include>org.mariadb.jdbc:mariadb-java-client</include>
                <include>org.ogce:xpp5</include>
                <include>commons-lang:commons-lang</include>
                <include>org.springframework.cloud:spring-cloud-context</include>
                <include>io.zipkin.brave:brave-instrumentation-spring-webmvc</include>
                <include>io.sundr:sundr-codegen</include>
                <include>org.apache.airavata:services-security</include>
                <include>org.springframework:spring-core</include>
                <include>org.springframework:spring-expression</include>
                <include>org.apache.custos:user-management-client</include>
                <include>com.fasterxml.jackson.module:jackson-module-jaxb-annotations</include>
                <include>edu.uiuc.ncsa.security.delegation:ncsa-security-delegation-server</include>
                <include>commons-configuration:commons-configuration</include>
                <include>aopalliance:aopalliance</include>
                <include>jakarta.annotation:jakarta.annotation-api</include>
                <include>io.zipkin.reporter2:zipkin-sender-amqp-client</include>
                <include>io.zipkin.brave:brave-instrumentation-rpc</include>
                <include>com.google.android:annotations</include>
                <include>io.netty:netty-buffer</include>
                <include>org.springframework.cloud:spring-cloud-sleuth-zipkin</include>
                <include>ch.qos.logback:logback-classic</include>
                <include>javax.xml.bind:jaxb-api</include>
                <include>org.lz4:lz4-java</include>
                <include>org.apache.httpcomponents:httpclient</include>
                <include>io.netty:netty-handler</include>
                <include>com.google.code.findbugs:jsr305</include>
                <include>org.apache.servicemix.bundles:org.apache.servicemix.bundles.xpp3</include>
                <include>com.fasterxml.jackson.core:jackson-databind</include>
                <include>javax.activation:javax.activation-api</include>
                <include>org.apache.airavata:airavata-base-api</include>
                <include>org.springframework:spring-webmvc</include>
                <include>org.hibernate.validator:hibernate-validator</include>
                <include>io.sundr:sundr-core</include>
                <include>org.aspectj:aspectjrt</include>
                <include>org.apache.commons:commons-collections4</include>
                <include>com.fasterxml.jackson.module:jackson-module-parameter-names</include>
                <include>org.apache.airavata:airavata-sharing-registry-server</include>
                <include>net.oauth.core:oauth</include>
                <include>org.apache.servicemix.bundles:org.apache.servicemix.bundles.antlr</include>
                <include>org.apache.custos:group-management-service</include>
                <include>org.apache.custos:federated-authentication-core-service-client-stub</include>
                <include>org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec</include>
                <include>org.beanshell:bsh</include>
                <include>org.apache.directory.api:api-all</include>
                <include>org.apache.airavata:airavata-messaging-core</include>
                <include>org.springframework.boot:spring-boot-actuator-autoconfigure</include>
                <include>io.grpc:grpc-core</include>
                <include>org.springframework.security:spring-security-crypto</include>
                <include>c3p0:c3p0</include>
                <include>org.codehaus.jackson:jackson-mapper-asl</include>
                <include>net.sf.dozer:dozer</include>
                <include>net.jcip:jcip-annotations</include>
                <include>io.prometheus:simpleclient_hotspot</include>
                <include>org.springframework.cloud:spring-cloud-sleuth-core</include>
                <include>io.kubernetes:client-java</include>
                <include>org.apache.derby:derby</include>
                <include>io.netty:netty-common</include>
                <include>org.apache.xbean:xbean-asm7-shaded</include>
                <include>org.jmockit:jmockit</include>
                <include>mysql:mysql-connector-java</include>
                <include>org.jboss.netty:netty</include>
                <include>org.quartz-scheduler:quartz-jobs</include>
                <include>io.netty:netty-codec-http</include>
                <include>org.slf4j:slf4j-log4j12</include>
                <include>org.hdrhistogram:HdrHistogram</include>
                <include>org.apache.airavata:db-event-manager</include>
            </includes>
            <excludes>
                <exclude>mysql:mysql-connector-java</exclude>
            </excludes>
        </dependencySet>

    </dependencySets>

</assembly>
